name: ServerRules
main: kenygamer\ServerRules\Main
version: 1.3.0
api: 3.0.0
author: kenygamer
website: github.com/kenygamer/ServerRules
commands:
    rules:
        usage: /rules
        description: Displays all the server rules
permissions:
    command.rules:
        default: true
        description: Allows players to use the /rules command
