name: ServerRules
description: List the rules of your server in a command
author: kenygamer
main: kenygamer\ServerRules\Main
load: POSTWORLD
version: 1.0.0
api: 3.0.0
commands:
    rules:
        usage: /rules
        description: Displays the list of the server rules
permissions:
    command.rules:
        default: true
        description: Allow players to use the /rules command
