name: ServerRules
main: kenygamer\ServerRules\Main
version: 1.0.0
api: [3.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7]
author: Zeao
website: §cNot showing due to self-leak information.
commands:
 rules:
  usage: /rules
  description: Displays all the server rules
permissions:
 command.rules:
  default: true
  description: Allows players to use the /rules command
