# Enter the server rules below between the quotation marks
rules:
 - "1.-"
 - "2.-"
 - "3.- "
 - "4.- "
 - "5.- "
 
# You can add rules inserting a space and then - ""
# If you want to remove rules remove the whole line
...
